import Link from "next/link";
import {redirect} from "next/navigation";
import {neon} from "@neondatabase/serverless";
import {getCustomerForSession} from "@/lib/portal";
export const dynamic="force-dynamic";
export default async function MijnIselto(){
 const result=await getCustomerForSession();if(!result)redirect("/mijn-iselto/onboarding");
 const {customer,user}=result;const db=neon(process.env.DATABASE_URL!);
 const [machines,contracts,tickets,orders]=await Promise.all([
  db\`select count(*)::int as count from public."Machine" where "customerId"=${customer.id}\`,
  db\`select count(*)::int as count from public."Contract" where "customerId"=${customer.id} and status='active'\`,
  db\`select count(*)::int as count from public."ServiceTicket" where "customerId"=${customer.id} and status not in ('resolved','closed')\`,
  db\`select count(*)::int as count from public."TonerOrder" where "customerId"=${customer.id} and status not in ('delivered','cancelled')\`
 ]);
 const recent=await db\`select number,subject,status,priority,"createdAt" from public."ServiceTicket" where "customerId"=${customer.id} order by "createdAt" desc limit 5\`;
 return <><div className="portal-top"><div className="portal-top-inner"><div className="portal-brand">Mijn <span>Iselto</span></div><div className="portal-user">{user.name||user.email}</div></div></div><nav className="portal-nav"><div className="portal-nav-inner"><Link href="/mijn-iselto">Overzicht</Link><Link href="/mijn-iselto/machines">Machines</Link><Link href="/mijn-iselto/contracten">Contracten</Link><Link href="/mijn-iselto/storingen">Storingen</Link><Link href="/mijn-iselto/toners">Toners</Link><Link href="/mijn-iselto/documenten">Documenten</Link><Link href="/mijn-iselto/standen">Meterstanden</Link><Link href="/mijn-iselto/account">Account</Link></div></nav><main className="portal-wrap"><div className="portal-main-head"><div><div className="portal-label">Klantnummer {customer.customerNumber}</div><h1>Goedemorgen, {user.name?.split(" ")[0]||"daar"}</h1><p>Alles rondom je printomgeving op één plek.</p></div><div className="portal-actions"><Link className="portal-btn primary" href="/mijn-iselto/storingen/nieuw">Storing melden</Link><Link className="portal-btn" href="/mijn-iselto/toners">Toner bestellen</Link></div></div><div className="portal-grid"><div className="portal-card"><div className="portal-label">Machines</div><div className="portal-stat">{machines[0]?.count||0}</div></div><div className="portal-card"><div className="portal-label">Actieve contracten</div><div className="portal-stat">{contracts[0]?.count||0}</div></div><div className="portal-card"><div className="portal-label">Open storingen</div><div className="portal-stat">{tickets[0]?.count||0}</div></div><div className="portal-card"><div className="portal-label">Lopende tonerorders</div><div className="portal-stat">{orders[0]?.count||0}</div></div></div><div className="portal-section-grid portal-section"><section className="portal-card"><h2>Recente storingen</h2>{recent.length?<div className="portal-list">{recent.map((x:any)=><div className="portal-list-item" key={x.number}><div><strong>{x.number} · {x.subject}</strong><br/><small>{new Date(x.createdAt).toLocaleDateString("nl-NL")}</small></div><span className={"portal-badge "+(x.status==="open"?"red":x.status==="in_progress"?"orange":"green")}>{x.status==="in_progress"?"In behandeling":x.status==="resolved"?"Opgelost":x.status}</span></div>)}</div>:<div className="portal-empty">Nog geen storingen gemeld.</div>}</section><section className="portal-card"><h2>Snel naar</h2><div className="portal-list"><Link className="portal-list-item" href="/mijn-iselto/machines"><strong>Mijn machines</strong><span>→</span></Link><Link className="portal-list-item" href="/mijn-iselto/contracten"><strong>Contracten & looptijd</strong><span>→</span></Link><Link className="portal-list-item" href="/mijn-iselto/documenten"><strong>Contractdocumenten</strong><span>→</span></Link><Link className="portal-list-item" href="/mijn-iselto/standen"><strong>Meterstanden doorgeven</strong><span>→</span></Link></div></section></div></main></>
}
