import Link from "next/link";
import {products} from "@/lib/products";
export const metadata={title:"A3 multifunctionals voor bedrijven",description:"A3 multifunctionals voor zakelijke organisaties: kleur en zwart-wit, van 25 tot 70 ppm. Vergelijk onze MFP's en vraag advies of een offerte.",alternates:{canonical:"/producten/a3-multifunctionals"},openGraph:{type:"website",title:"A3 multifunctionals voor bedrijven",description:"A3 multifunctionals voor zakelijke organisaties: kleur en zwart-wit, van 25 tot 70 ppm. Vergelijk onze MFP's en vraag advies of een offerte.",url:"https://mfp.iselto.nl/producten/a3-multifunctionals"}};
export default function A3Page(){
 const items=products.filter(p=>p.format.includes("A3"));
 return <main>
  <section className="dark-hero"><div className="container hero-copy"><div className="eyebrow eyebrow-light">A3 MULTIFUNCTIONALS</div><h1>A3 printen, scannen en kopiëren voor uw organisatie.</h1><p>Voor kantoren en werkomgevingen waar A3, hogere volumes, uitgebreide papierverwerking of professionele afwerking onderdeel zijn van het dagelijkse werk.</p><div className="hero-actions"><Link className="btn btn-light" href="/mfp-kiezen">Vind mijn MFP</Link><Link className="btn btn-outline-light" href="/offerte">Vraag advies</Link></div></div></section>
  <section className="container editorial-section"><div className="section-intro"><div><div className="eyebrow">WAAROM A3?</div><h2>Meer dan alleen een groter papierformaat.</h2></div><div><p className="lead">A3-systemen zijn interessant wanneer u met grotere documenten werkt, meer papiercapaciteit nodig heeft, veel scant of professionele afwerking wilt inzetten. De juiste configuratie hangt af van volume, kleurgebruik, scanwerk en gewenste afwerking.</p></div></div></section>
  <section className="container catalog-section"><div className="section-head"><div><div className="eyebrow">A3 PORTFOLIO</div><h2>{items.length} modellen.</h2></div><Link className="btn btn-secondary" href="/vergelijker">Vergelijk modellen</Link></div><div className="product-grid">{items.map(p=><Link href={"/producten/"+p.slug} className="card product-card" key={p.slug}><div className="product-image"><img src={p.image} alt={p.name} className="product-image-element" loading="lazy"/></div><div className="product-copy"><div className="eyebrow">{p.category}</div><h3>{p.name}</h3><p>{p.description}</p><div className="product-specs"><span>{p.speed}</span><span>{p.colour?"Kleur":"Zwart-wit"}</span><span>{p.format}</span></div><b>Bekijk specificaties →</b></div></Link>)}</div></section>
  <section className="split-section"><div className="container split-grid"><div><div className="eyebrow">ONTZORGD LEVEREN</div><h2>Ook de financiering en service kunnen we meenemen.</h2></div><div><p className="large-copy">Lease, huur of koop. Bespreek daarnaast een service- of all-in contract, zodat niet alleen de machine maar ook de continuïteit van uw printomgeving geregeld is.</p><Link className="btn btn-primary" href="/offerte">Vraag een voorstel</Link></div></div></section>
 <section className="container editorial-section"><div className="seo-article"><h2>A3 multifunctionele printer voor zakelijke toepassingen</h2><p>Een A3 multifunctional is bedoeld voor organisaties die naast standaard kantooroutput ook grotere documenten, technische informatie, presentaties of andere A3-formaten verwerken. Kijk naar printsnelheid, scansnelheid, papiercapaciteit en afwerking in samenhang met uw werkproces.</p><p>Lees ook onze gids over <Link className="text-link" href="/kennis/a4-of-a3-mfp">A4 of A3 kiezen</Link> en gebruik de <Link className="text-link" href="/vergelijker">MFP vergelijker</Link>.</p></div></section></main>;
}