import Link from "next/link";
import {products} from "@/lib/products";
export const metadata={title:"Kyocera TASKalfa MZ-serie | A3 multifunctionals",description:"Bekijk de Kyocera TASKalfa MZ-serie: A3 kleuren- en zwart-wit multifunctionals van 25 tot 70 ppm. Vergelijk specificaties en vraag advies."};
export default function MzSeries(){
 const items=products.filter(p=>p.name.startsWith("TASKalfa MZ"));
 return <main>
  <section className="dark-hero"><div className="container hero-copy"><div className="eyebrow eyebrow-light">TASKALFA MZ-SERIE</div><h1>Een complete A3-serie voor moderne documentstromen.</h1><p>De MZ-serie combineert A3 printen, scannen en kopiëren met cloud-ready oplossingen, beveiliging, AI-functionaliteiten en flexibele papier- en afwerkingsopties. De serie loopt van compacte zakelijke modellen tot systemen voor hoge volumes.</p><div className="hero-actions"><Link className="btn btn-light" href="/mfp-kiezen">Vind mijn MFP</Link><Link className="btn btn-outline-light" href="/offerte">Vraag advies</Link></div></div></section>
  <section className="container editorial-section"><div className="section-intro"><div><div className="eyebrow">DE SERIE</div><h2>Van 25 tot 70 ppm A4.</h2></div><div><p className="lead">Binnen de serie zijn kleur en zwart-wit beschikbaar. De hogere modellen bieden daarnaast uitgebreide papiercapaciteit en afwerkingsmogelijkheden. Kyocera beschrijft de MZ7001ci-serie als gericht op digitale workflows en cloud, met data capture, AI, gebruiksvriendelijke bediening en beveiliging.</p></div></div></section>
  <section className="container catalog-section"><div className="section-head"><div><div className="eyebrow">MODELLEN</div><h2>{items.length} MZ-modellen in ons portfolio.</h2></div><Link className="btn btn-secondary" href="/vergelijker">Vergelijk</Link></div><div className="product-grid">{items.map(p=><Link href={"/producten/"+p.slug} className="card product-card" key={p.slug}><div className="product-image"><img src={p.image} alt={p.name} className="product-image-element" loading="lazy"/></div><div className="product-copy"><div className="eyebrow">{p.category}</div><h3>{p.name}</h3><p>{p.description}</p><div className="product-specs"><span>{p.speed}</span><span>{p.colour?"Kleur":"Zwart-wit"}</span><span>{p.format}</span></div><b>Bekijk model →</b></div></Link>)}</div></section>
  <section className="split-section"><div className="container split-grid"><div><div className="eyebrow">PERSOONLIJK ADVIES</div><h2>De juiste MZ-configuratie hangt af van uw werk.</h2></div><div><p className="large-copy">Naast het basisapparaat zijn documenttoevoer, papierladen, finisher, scanworkflow, beveiliging en software belangrijk. Wij kunnen de configuratie afstemmen op uw organisatie.</p><Link className="btn btn-primary" href="/offerte">Bespreek uw situatie</Link></div></div></section>
 </main>;
}