import Link from "next/link";
import {redirect,notFound} from "next/navigation";
import {neon} from "@neondatabase/serverless";
import {getCustomerForSession} from "@/lib/portal";
import {TicketForm} from "../storingen-form";
import {TonerForm} from "../toner-form";
import {MeterForm} from "../meter-form";
import {AccountClient} from "../account-client";
export const dynamic="force-dynamic";
function shell(user:any,children:React.ReactNode){return <><div className="portal-top"><div className="portal-top-inner"><div className="portal-brand">Mijn <span>Iselto</span></div><div className="portal-user">{user.name||user.email}</div></div></div><nav className="portal-nav"><div className="portal-nav-inner"><Link href="/mijn-iselto">Overzicht</Link><Link href="/mijn-iselto/machines">Machines</Link><Link href="/mijn-iselto/contracten">Contracten</Link><Link href="/mijn-iselto/storingen">Storingen</Link><Link href="/mijn-iselto/toners">Toners</Link><Link href="/mijn-iselto/documenten">Documenten</Link><Link href="/mijn-iselto/standen">Meterstanden</Link><Link href="/mijn-iselto/account">Account</Link></div></nav><main className="portal-wrap">{children}</main></>}
export default async function SectionPage({params}:{params:Promise<{section:string[]}>}){
 const {section}=await params;const result=await getCustomerForSession();if(!result)redirect("/mijn-iselto/onboarding");
 const {customer,user}=result;const db=neon(process.env.DATABASE_URL!);const key=section.join("/");
 if(key==="machines"){const rows=await db\`select m.*,c."contractNumber" from public."Machine" m left join public."Contract" c on c.id=m."contractId" where m."customerId"=${customer.id} order by m.location nulls last,m.model\`;return shell(user,<><div className="portal-main-head"><div><div className="portal-label">Mijn apparatuur</div><h1>Machines</h1><p>Een actueel overzicht van alle machines die bij jouw organisatie bekend zijn.</p></div></div><div className="portal-table-wrap"><table className="portal-table"><thead><tr><th>Machine</th><th>Serienummer</th><th>Locatie</th><th>Contract</th><th>Stand zwart</th><th>Stand kleur</th><th>Status</th></tr></thead><tbody>{rows.map((m:any)=><tr key={m.id}><td><strong>{m.brand} {m.model}</strong><br/><small>{m.assetNumber}</small></td><td>{m.serialNumber||"—"}</td><td>{m.location||"—"}</td><td>{m.contractNumber||"—"}</td><td>{m.meterBlack.toLocaleString("nl-NL")}</td><td>{m.meterColor.toLocaleString("nl-NL")}</td><td><span className="portal-badge green">{m.status==="active"?"Actief":m.status}</span></td></tr>)}</tbody></table>{!rows.length&&<div className="portal-empty">Er zijn nog geen machines aan deze klantomgeving gekoppeld.</div>}</div></>)}
 if(key==="contracten"){const rows=await db\`select * from public."Contract" where "customerId"=${customer.id} order by "startDate" desc\`;return shell(user,<><div className="portal-main-head"><div><div className="portal-label">Afspraken & looptijden</div><h1>Contracten</h1><p>Bekijk looptijd, contracttype, status en de bijbehorende documenten.</p></div></div><div className="portal-table-wrap"><table className="portal-table"><thead><tr><th>Contract</th><th>Type</th><th>Start</th><th>Einde</th><th>Status</th><th>Opzegtermijn</th><th>Bedrag</th></tr></thead><tbody>{rows.map((c:any)=><tr key={c.id}><td><strong>{c.contractNumber}</strong><br/><small>{c.title}</small></td><td>{c.type}</td><td>{new Date(c.startDate).toLocaleDateString("nl-NL")}</td><td>{c.endDate?new Date(c.endDate).toLocaleDateString("nl-NL"):"Doorlopend"}</td><td><span className="portal-badge green">{c.status}</span></td><td>{c.noticePeriodMonths?c.noticePeriodMonths+" maanden":"—"}</td><td>{c.monthlyAmountCents?new Intl.NumberFormat("nl-NL",{style:"currency",currency:"EUR"}).format(c.monthlyAmountCents/100):"—"}</td></tr>)}</tbody></table>{!rows.length&&<div className="portal-empty">Er zijn nog geen contracten gekoppeld.</div>}</div></>)}
 if(key==="storingen"){const rows=await db\`select s.*,m.brand,m.model from public."ServiceTicket" s left join public."Machine" m on m.id=s."machineId" where s."customerId"=${customer.id} order by s."createdAt" desc\`;return shell(user,<><div className="portal-main-head"><div><div className="portal-label">Service</div><h1>Storingen</h1><p>Volg meldingen en houd contact over lopende servicevragen.</p></div><Link className="portal-btn primary" href="/mijn-iselto/storingen/nieuw">Storing melden</Link></div><div className="portal-table-wrap"><table className="portal-table"><thead><tr><th>Nummer</th><th>Melding</th><th>Machine</th><th>Prioriteit</th><th>Status</th><th>Datum</th></tr></thead><tbody>{rows.map((s:any)=><tr key={s.id}><td><strong>{s.number}</strong></td><td>{s.subject}<br/><small>{s.description.slice(0,120)}{s.description.length>120?"…":""}</small></td><td>{s.brand?s.brand+" "+s.model:"—"}</td><td>{s.priority}</td><td><span className={"portal-badge "+(s.status==="open"?"red":s.status==="in_progress"?"orange":"green")}>{s.status==="in_progress"?"In behandeling":s.status==="resolved"?"Opgelost":s.status}</span></td><td>{new Date(s.createdAt).toLocaleDateString("nl-NL")}</td></tr>)}</tbody></table>{!rows.length&&<div className="portal-empty">Nog geen storingen gemeld.</div>}</div></>)}
 if(key==="storingen/nieuw")return shell(user,<><div className="portal-main-head"><div><div className="portal-label">Service</div><h1>Storing melden</h1><p>Beschrijf wat er aan de hand is.</p></div></div><TicketForm/></>);
 if(key==="toners"){const products=await db\`select * from public."TonerProduct" where "isActive"=true order by name\`;const orders=await db\`select * from public."TonerOrder" where "customerId"=${customer.id} order by "createdAt" desc limit 10\`;return shell(user,<><div className="portal-main-head"><div><div className="portal-label">Verbruiksmaterialen</div><h1>Toners bestellen</h1><p>Bestel eenvoudig de toners die bij jouw machines horen.</p></div></div><TonerForm products={products}/><section className="portal-section portal-card"><h2>Recente tonerorders</h2>{orders.length?<div className="portal-list">{orders.map((o:any)=><div className="portal-list-item" key={o.id}><div><strong>{o.number}</strong><br/><small>{new Date(o.createdAt).toLocaleDateString("nl-NL")}</small></div><span className="portal-badge">{o.status}</span></div>)}</div>:<div className="portal-empty">Nog geen tonerorders.</div>}</section></>)}
 if(key==="documenten"){const docs=await db\`select d.*,c."contractNumber" from public."Document" d left join public."Contract" c on c.id=d."contractId" where d."customerId"=${customer.id} order by d."createdAt" desc\`;return shell(user,<><div className="portal-main-head"><div><div className="portal-label">Privé documenten</div><h1>Documenten</h1><p>Contracten en andere documenten die Iselto voor jouw organisatie beschikbaar heeft gesteld.</p></div></div><section className="portal-card">{docs.length?docs.map((d:any)=><div className="portal-list-item" key={d.id}><div><strong>{d.title}</strong><br/><small>{d.fileName} · {d.contractNumber||d.category}</small></div><Link className="portal-btn" href={"/api/portal/documents/"+d.id}>Openen</Link></div>):<div className="portal-empty">Er zijn nog geen documenten beschikbaar.</div>}</section></>)}
 if(key==="standen"){const machines=await db\`select id,brand,model,"assetNumber","meterBlack","meterColor" from public."Machine" where "customerId"=${customer.id} and status='active' order by model\`;return shell(user,<><div className="portal-main-head"><div><div className="portal-label">Verbruik</div><h1>Meterstanden</h1><p>Geef per machine de actuele tellerstanden door.</p></div></div><MeterForm machines={machines}/></>)}
 if(key==="account")return shell(user,<><div className="portal-main-head"><div><div className="portal-label">Mijn gegevens</div><h1>Account</h1><p>Beheer je account en sessie.</p></div></div><div className="portal-card"><div className="portal-detail-grid"><div className="portal-detail"><span>Naam</span><strong>{user.name||"—"}</strong></div><div className="portal-detail"><span>E-mailadres</span><strong>{user.email}</strong></div><div className="portal-detail"><span>Bedrijf</span><strong>{customer.name}</strong></div><div className="portal-detail"><span>Klantnummer</span><strong>{customer.customerNumber}</strong></div></div><AccountClient/></div></>);
 return notFound();
}
