import {NextResponse} from "next/server";import {z} from "zod";import {Resend} from "resend";import {prisma} from "@/lib/db";
const schema=z.object({type:z.enum(["quote","contact"]),name:z.string().trim().min(2).max(120),company:z.string().trim().max(160).optional(),email:z.string().trim().email().max(254),phone:z.string().trim().max(50).optional(),city:z.string().trim().max(120).optional(),message:z.string().trim().max(4000).optional(),product:z.string().trim().max(120).optional(),website:z.string().trim().max(200).optional()});
const rateLimit=new Map<string,{count:number;resetAt:number}>();const WINDOW_MS=10*60*1000;const MAX_REQUESTS=5;
function escapeHtml(value:string){return value.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#039;");}
function clientKey(req:Request){return req.headers.get("x-forwarded-for")?.split(",")[0]?.trim()||req.headers.get("x-real-ip")||"unknown";}
function isSameOrigin(req:Request){const origin=req.headers.get("origin");if(!origin)return true;try{return new URL(origin).host===new URL(req.url).host;}catch{return false;}}
function limited(key:string){const now=Date.now();const current=rateLimit.get(key);if(!current||current.resetAt<=now){rateLimit.set(key,{count:1,resetAt:now+WINDOW_MS});return false;}current.count+=1;return current.count>MAX_REQUESTS;}
function json(data:unknown,status=200){return NextResponse.json(data,{status,headers:{"Cache-Control":"no-store"}});}
export async function POST(req:Request){try{
 if(!isSameOrigin(req))return json({error:"Ongeldige aanvraag."},403);if(limited(clientKey(req)))return json({error:"Te veel aanvragen. Probeer het over enkele minuten opnieuw."},429);if(!(req.headers.get("content-type")||"").toLowerCase().includes("application/json"))return json({error:"Ongeldige aanvraag."},415);
 const raw=await req.text();if(raw.length>16000)return json({error:"Aanvraag is te groot."},413);let payload:unknown;try{payload=JSON.parse(raw);}catch{return json({error:"Ongeldige aanvraag."},400);}
 const parsed=schema.safeParse(payload);if(!parsed.success)return json({error:"Controleer de ingevulde gegevens."},400);const data=parsed.data;if(data.website)return json({ok:true});
 if(!process.env.DATABASE_URL)return json({error:"Leadopslag is nog niet geconfigureerd."},503);if(!process.env.RESEND_API_KEY)return json({error:"E-mailverzending is nog niet geconfigureerd."},503);
 await prisma.lead.create({data:{type:data.type,name:data.name,company:data.company||undefined,email:data.email,phone:data.phone||undefined,city:data.city||undefined,message:data.message||undefined,product:data.product||undefined}});
 const resend=new Resend(process.env.RESEND_API_KEY);const recipient=process.env.LEAD_EMAIL_TO||"bram.derks@outlook.com";const sender=process.env.LEAD_EMAIL_FROM||"MFP ISELTO <aanvragen@iselto.nl>";const subject=data.type==="quote"?`Nieuwe offerteaanvraag – ${data.product||"MFP advies"}`:"Nieuwe contactaanvraag – MFP ISELTO";
 const {error}=await resend.emails.send({from:sender,to:[recipient],replyTo:data.email,subject,html:`<div style="font-family:Arial,sans-serif;line-height:1.6;color:#17202a;max-width:700px"><h1 style="font-size:24px">Nieuwe ${data.type==="quote"?"offerteaanvraag":"contactaanvraag"}</h1><p>Er is een nieuwe aanvraag binnengekomen via mfp.iselto.nl.</p><table cellpadding="8" cellspacing="0" style="border-collapse:collapse;width:100%"><tr><td><strong>Naam</strong></td><td>${escapeHtml(data.name)}</td></tr><tr><td><strong>Bedrijf</strong></td><td>${escapeHtml(data.company||"-")}</td></tr><tr><td><strong>E-mail</strong></td><td>${escapeHtml(data.email)}</td></tr><tr><td><strong>Telefoon</strong></td><td>${escapeHtml(data.phone||"-")}</td></tr><tr><td><strong>Plaats</strong></td><td>${escapeHtml(data.city||"-")}</td></tr><tr><td><strong>MFP</strong></td><td>${escapeHtml(data.product||"Nog te bepalen")}</td></tr></table><h2 style="font-size:18px;margin-top:24px">Vraag / wensen</h2><p style="white-space:pre-wrap">${escapeHtml(data.message||"-")}</p></div>`});
 if(error)return json({ok:false,error:"De aanvraag is opgeslagen, maar de e-mail kon niet worden verzonden. Neem contact met ons op als dit blijft gebeuren."},502);return json({ok:true});
}catch{return json({error:"Kon aanvraag niet verwerken."},500);}}
