import type {Metadata} from "next";
import Link from "next/link";
import Image from "next/image";
import "./globals.css";
import "./refinement.css";
import "./suite.css";

const siteUrl="https://mfp.iselto.nl";
const organizationJsonLd={"@context":"https://schema.org","@type":"Organization","@id":siteUrl+"/#organization","name":"MFP Iselto","url":siteUrl,"logo":siteUrl+"/iselto-logo.svg","description":"B2B print-, scan-, MFP- en documentoplossingen voor organisaties in de Benelux","areaServed":["NL","BE","LU"],"knowsAbout":["Multifunctionals","MFP","Print management","Document management","OCR","Workflow software"]};
const websiteJsonLd={"@context":"https://schema.org","@type":"WebSite","@id":siteUrl+"/#website","name":"MFP Iselto","url":siteUrl,"publisher":{"@id":siteUrl+"/#organization"},"inLanguage":"nl-NL","potentialAction":{"@type":"SearchAction","target":{"@type":"EntryPoint","urlTemplate":siteUrl+"/zoeken?q={search_term_string}"},"query-input":"required name=search_term_string"}};

export const metadata:Metadata={title:{default:"MFP Iselto | Zakelijke multifunctionals, print & scan",template:"%s | MFP Iselto"},description:"MFP Iselto helpt organisaties met zakelijke multifunctionals, printers, documentoplossingen en persoonlijke service.",metadataBase:new URL(siteUrl),alternates:{canonical:"/"},openGraph:{type:"website",locale:"nl_NL",url:siteUrl,siteName:"MFP Iselto",title:"MFP Iselto | Zakelijke multifunctionals, print & scan",description:"Zakelijke multifunctionals, printsoftware, managed print en service. Persoonlijk advies voor uw complete printomgeving.",images:[{url:"/iselto-logo.svg",alt:"MFP Iselto"}]},twitter:{card:"summary",title:"MFP Iselto | Zakelijke multifunctionals, print & scan",description:"Zakelijke multifunctionals, printsoftware, managed print en service."}};

export default function RootLayout({children}:{children:React.ReactNode}){
 return <html lang="nl"><body><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(organizationJsonLd)}}/><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(websiteJsonLd)}}/><div className="topbar"><div className="container topbar-inner"><span>25 jaar ervaring in de printbranche</span><span>Persoonlijk advies · Passende techniek · Service</span></div></div><header className="site-header"><div className="container header-inner"><Link href="/" className="logo-link" aria-label="MFP Iselto home"><Image src="/iselto-logo.svg" alt="MFP Iselto" width={285} height={68} priority/></Link><nav className="desktop-nav" aria-label="Hoofdnavigatie"><Link href="/producten">MFP's</Link><Link href="/oplossingen">Oplossingen</Link><Link href="/software">Software</Link><Link href="/managed-print">Managed print</Link><Link href="/service">Service</Link><Link href="/over-iselto">Over Iselto</Link><Link className="btn btn-primary nav-cta" href="/offerte">Offerte aanvragen</Link></nav><nav className="mobile-nav" aria-label="Mobiele navigatie"><Link href="/producten">MFP's</Link><Link href="/software">Software</Link><Link href="/zoeken">Zoeken</Link><Link className="btn btn-primary" href="/offerte">Offerte</Link></nav></div></header>{children}<footer className="site-footer"><div className="container footer-grid"><div className="footer-brand"><div className="footer-wordmark" aria-label="MFP Iselto">MFP <span>Iselto</span></div><p>Zakelijke MFP's, printsoftware, managed print en service voor organisaties in de Benelux.</p><p className="footer-muted">25 jaar ervaring · 1.000+ zakelijke klanten in de Benelux.</p></div><div><b>MFP's</b><p><Link href="/producten">Alle MFP's</Link></p><p><Link href="/mfp-kiezen">MFP keuzehulp</Link></p><p><Link href="/vergelijker">MFP vergelijker</Link></p><p><Link href="/lease-huur-koop">Lease · huur · koop</Link></p><p><Link href="/tco-scan">TCO-scan</Link></p></div><div><b>Oplossingen</b><p><Link href="/software">Software</Link></p><p><Link href="/oplossingen">Documentoplossingen</Link></p><p><Link href="/managed-print">Managed print</Link></p><p><Link href="/service">Service & support</Link></p><p><Link href="/branches">Per branche</Link></p></div><div><b>Iselto</b><p><Link href="/klantverhalen">Klantverhalen</Link></p><p><Link href="/faq">Veelgestelde vragen</Link></p><p><Link href="/over-iselto">Over Iselto</Link></p><p><Link href="/vacatures">Vacatures</Link></p><p><Link href="/contact">Contact</Link></p></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} MFP Iselto</span><span>PRINT · SCAN · MANAGE</span></div></footer></body></html>; }