import Link from "next/link";
const software=[["01","OCR & documentherkenning","Maak gescande documenten beter doorzoekbaar en bruikbaar in digitale processen.","OCR","Documentverwerking"],["02","Workflow automatisering","Laat documenten automatisch naar de juiste persoon, map, mailbox, printer of vervolgstap gaan.","Workflow","Routing"],["03","Cloud print management","Beheer gebruikers, printers en printopdrachten centraal vanuit de cloud.","Cloud","Print management"],["04","Beveiligd printen","Laat documenten pas vrijkomen na authenticatie en houd vertrouwelijke informatie onder controle.","Follow-me","Authenticatie"],["05","Document management","Orden, archiveer en vind documenten sneller met een passende digitale documentomgeving.","Archiveren","Zoeken"],["06","Output management","Automatiseer uitgaande documenten vanuit ERP, CRM of andere bedrijfssoftware.","ERP/CRM","Output"],["07","Scan to workflow","Laat scans direct naar een bedrijfsproces, opslaglocatie of applicatie gaan.","Scannen","Integratie"],["08","Mobiel & hybride werken","Ondersteun medewerkers die vanaf verschillende locaties en apparaten moeten kunnen printen.","Mobiel","Hybride"]].map(([n,title,text,a,b])=>({n,title,text,tags:[a,b]}));
export const metadata={title:"Print- en documentsoftware",description:"Software voor OCR, workflow, cloud print, beveiligd printen, document management en output management voor zakelijke organisaties.",alternates:{canonical:"/software"},openGraph:{type:"website",title:"Print- en documentsoftware",description:"Software voor OCR, workflow, cloud print, beveiligd printen, document management en output management voor zakelijke organisaties.",url:"https://mfp.iselto.nl/software"}};
export default function Software(){return <main>
<section className="dark-hero"><div className="container hero-copy"><div className="eyebrow eyebrow-light">SOFTWARE & DOCUMENTOPLOSSINGEN</div><h1>Meer uit uw documenten. Zonder extra handwerk.</h1><p>Een MFP is hardware. De software eromheen bepaalt steeds vaker hoe efficiënt, veilig en digitaal uw organisatie werkt.</p><div className="hero-actions"><Link className="btn btn-light" href="/contact">Bespreek software</Link><Link className="btn btn-outline-light" href="/producten">Bekijk MFP's</Link></div></div></section>
<section className="container editorial-section"><div className="section-intro"><div><div className="eyebrow">LOS VAN DE APPARATUUR</div><h2>Software die uw documentproces slimmer maakt.</h2></div><p className="lead">U hoeft niet direct een nieuwe MFP te kopen om documentprocessen te verbeteren. We kunnen ook kijken naar software, workflow en cloudoplossingen rondom uw bestaande omgeving.</p></div><div className="software-grid">{software.map(s=><article className="solution-card" key={s.n}><div className="solution-number">{s.n}</div><h3>{s.title}</h3><p>{s.text}</p><div className="tag-list">{s.tags.map(t=><span key={t}>{t}</span>)}</div><Link className="text-link" href="/contact">Meer informatie →</Link></article>)}</div></section>
<section className="split-section"><div className="container split-grid"><div><div className="eyebrow">OOK ZONDER NIEUWE MACHINE</div><h2>Uw bestaande omgeving kan het startpunt zijn.</h2></div><div><p className="large-copy">We kijken eerst naar uw huidige MFP's, systemen en documentstromen. Daarna bepalen we waar software waarde toevoegt en welke koppelingen nodig zijn.</p><Link className="btn btn-primary" href="/offerte">Vraag softwareadvies</Link></div></div></section>
<section className="container editorial-section"><div className="feature-banner"><div><div className="eyebrow">COMBINATIE</div><h2>Hardware + software + service.</h2><p>Een zakelijke printomgeving werkt pas echt als apparatuur, software en ondersteuning op elkaar aansluiten.</p></div><Link className="btn btn-primary" href="/managed-print">Managed print bekijken</Link></div></section>
<section className="container cta-section"><div className="cta-panel"><div><div className="eyebrow eyebrow-light">SOFTWARE ADVIES</div><h2>Welke workflow wilt u verbeteren?</h2><p>Vertel ons wat nu handmatig gaat. We bespreken welke softwareoplossingen daarbij passen.</p></div><Link className="btn btn-light" href="/contact">Plan een gesprek</Link></div></section>
</main>}