import Link from "next/link";
import {products} from "@/lib/products";
export const metadata={title:"A4 multifunctionals voor bedrijven",description:"A4 multifunctionals voor zakelijke werkgroepen. Bekijk kleuren-MFP's van Kyocera, vergelijk modellen en vraag een passend voorstel."};
export default function A4Page(){
 const items=products.filter(p=>p.format==="A4");
 return <main>
  <section className="dark-hero"><div className="container hero-copy"><div className="eyebrow eyebrow-light">A4 MULTIFUNCTIONALS</div><h1>Compacte zakelijke MFP's voor dagelijks kantoorwerk.</h1><p>A4 multifunctionals combineren printen, scannen en kopiëren in een oplossing die past bij kleine en middelgrote werkgroepen en afdelingen.</p><div className="hero-actions"><Link className="btn btn-light" href="/mfp-kiezen">Vind mijn MFP</Link><Link className="btn btn-outline-light" href="/offerte">Vraag offerte</Link></div></div></section>
  <section className="container editorial-section"><div className="section-intro"><div><div className="eyebrow">A4 VOOR KANTOOR</div><h2>Compact waar het kan, compleet waar het moet.</h2></div><div><p className="lead">Let bij A4 niet alleen op printsnelheid. Scanvolume, beveiliging, papiercapaciteit, cloudprint en de manier waarop medewerkers de MFP gebruiken bepalen mede welke configuratie past.</p></div></div></section>
  <section className="container catalog-section"><div className="section-head"><div><div className="eyebrow">A4 PORTFOLIO</div><h2>{items.length} modellen.</h2></div><Link className="btn btn-secondary" href="/vergelijker">Vergelijk modellen</Link></div><div className="product-grid">{items.map(p=><Link href={"/producten/"+p.slug} className="card product-card" key={p.slug}><div className="product-image"><img src={p.image} alt={p.name} className="product-image-element" loading="lazy"/></div><div className="product-copy"><div className="eyebrow">{p.category}</div><h3>{p.name}</h3><p>{p.description}</p><div className="product-specs"><span>{p.speed}</span><span>Kleur</span><span>A4</span></div><b>Bekijk specificaties →</b></div></Link>)}</div></section>
  <section className="container editorial-section"><div className="feature-banner"><div><div className="eyebrow">HULP BIJ DE KEUZE</div><h2>Niet zeker hoeveel snelheid u nodig heeft?</h2><p>Gebruik onze keuzehulp op basis van volume, snelheid, formaat en kleur.</p></div><div className="feature-actions"><Link className="btn btn-primary" href="/mfp-kiezen">Start keuzehulp</Link><Link className="text-link" href="/mfp-leasen">Bekijk lease →</Link></div></div></section>
 </main>;
}