import Link from "next/link";

const cases=[
 {type:"Fictief voorbeeld · zakelijke dienstverlening",title:"Minder losse printers, meer overzicht.",intro:"Een groeiend advieskantoor werkte met verschillende printers en multifunctionals, verspreid over meerdere teams.",problem:["Verschillende apparaten en drivers","Geen centraal inzicht in gebruik","Documenten werden regelmatig opnieuw geprint"],solution:["Inventarisatie per werkplek en team","Consolidatie naar een beperkt aantal passende MFP's","Beveiligd printen en centrale printinstellingen"],result:"De nieuwe inrichting geeft het team één duidelijke printomgeving en maakt beheer en ondersteuning eenvoudiger."},
 {type:"Fictief voorbeeld · logistiek",title:"Van papierstroom naar scanworkflow.",intro:"Een logistieke organisatie verwerkte dagelijks orderdocumenten, pakbonnen en formulieren tussen kantoor en operatie.",problem:["Veel handmatig scannen en benoemen","Documenten moesten naar verschillende dossiers","Papieren documenten bleven lang onderweg"],solution:["Scanprofielen op de MFP","OCR en automatische documentrouting","Heldere werkinstructies voor medewerkers"],result:"De documentstroom werd overzichtelijker en medewerkers besteden minder tijd aan handmatige tussenstappen."},
 {type:"Fictief voorbeeld · zorg & welzijn",title:"Veilig printen zonder extra gedoe.",intro:"Een organisatie met meerdere teams wilde vertrouwelijke documenten niet langer onbeheerd bij een printer laten liggen.",problem:["Printopdrachten bleven bij het apparaat liggen","Meerdere gebruikers deelden machines","Beveiliging moest aansluiten op de bestaande werkwijze"],solution:["Print release met gebruikersauthenticatie","Duidelijke gebruikersrechten","Begeleiding bij invoering en gebruik"],result:"Documenten worden pas vrijgegeven wanneer de medewerker zich bij de MFP identificeert en de printomgeving is eenvoudiger te beheren."}
];

export const metadata={title:"Klantverhalen en praktijkvoorbeelden",description:"Fictieve praktijkvoorbeelden van hoe zakelijke organisaties hun MFP-, print- en documentomgeving kunnen verbeteren."};

export default function Cases(){
 return <main>
  <section className="dark-hero"><div className="container hero-copy"><div className="eyebrow eyebrow-light">PRAKTIJKVOORBEELDEN</div><h1>Wat verandert er als print onderdeel wordt van de oplossing?</h1><p>Onderstaande cases zijn bewust fictieve voorbeelden. De situaties en resultaten zijn illustratief en bedoeld om te laten zien hoe een traject kan worden opgebouwd.</p><div className="hero-actions"><Link className="btn btn-light" href="/offerte">Bespreek uw situatie</Link><Link className="btn btn-outline-light" href="/mfp-kiezen">Start de keuzehulp</Link></div></div></section>
  <section className="container editorial-section"><div className="case-grid">{cases.map((c,i)=><article className="case-card" key={c.title}><div className="case-number">0{i+1}</div><span>{c.type}</span><h2>{c.title}</h2><p className="case-intro">{c.intro}</p><div className="case-columns"><div><strong>Vraagstuk</strong><ul>{c.problem.map(x=><li key={x}>{x}</li>)}</ul></div><div><strong>Aanpak</strong><ul>{c.solution.map(x=><li key={x}>{x}</li>)}</ul></div></div><div className="case-result"><strong>Resultaat</strong><p>{c.result}</p></div></article>)}</div></section>
  <section className="container cta-section"><div className="cta-panel"><div><div className="eyebrow eyebrow-light">UW SITUATIE</div><h2>Uw organisatie is natuurlijk anders.</h2><p>Vertel ons wat er nu gebeurt. We vertalen dat naar een praktische print- en documentoplossing.</p></div><Link className="btn btn-light" href="/contact">Vertel uw situatie</Link></div></section>
 </main>;
}
