import Link from "next/link";
import MfpSelector from "@/components/MfpSelector";
export const metadata={title:"Zakelijke MFP's voor bedrijven",description:"Zakelijke multifunctionals voor bedrijven: A4 en A3, kleur en zwart-wit, met lease, huur, koop, all-in service en persoonlijk advies.",alternates:{canonical:"/zakelijke-mfp"},openGraph:{type:"website",title:"Zakelijke MFP's voor bedrijven",description:"Zakelijke multifunctionals voor bedrijven: A4 en A3, kleur en zwart-wit, met lease, huur, koop, all-in service en persoonlijk advies.",url:"https://mfp.iselto.nl/zakelijke-mfp"}};
export default function ZakelijkeMfp(){return <main>
<section className="dark-hero"><div className="container hero-copy"><div className="eyebrow eyebrow-light">ZAKELIJKE MFP</div><h1>De juiste multifunctional voor uw bedrijf.</h1><p>Van compacte A4 MFP tot krachtige A3 multifunctional. ISELTO helpt zakelijke organisaties kiezen, financieren, installeren en beheren.</p><div className="hero-actions"><Link className="btn btn-light" href="/producten#mfp-kiezen">Vind mijn MFP</Link><Link className="btn btn-outline-light" href="/offerte">Vraag offerte aan</Link></div></div></section>
<section className="container editorial-section"><div className="section-intro"><div><div className="eyebrow">VOLLEDIG B2B</div><h2>Niet de goedkoopste machine. Wel een oplossing die klopt.</h2></div><p className="lead">Wij kijken naar printvolume, gebruikers, papierformaten, scanwerk, beveiliging, afwerking en uw manier van werken. Daarna bepalen we welke MFP en welk contract daarbij passen.</p></div><div className="selector-benefits"><article><strong>A4 of A3</strong><span>Voor kantoor, afdeling of organisatie.</span></article><article><strong>Kleur of zwart-wit</strong><span>Op basis van uw documenten en kostenstructuur.</span></article><article><strong>Lease, huur of koop</strong><span>Een financiële vorm die past bij uw situatie.</span></article><article><strong>All-in service</strong><span>Apparatuur, onderhoud en ondersteuning als één oplossing.</span></article></div></section>
<MfpSelector/>
<section className="split-section"><div className="container split-grid"><div><div className="eyebrow">FINANCIERING</div><h2>Houd uw werkkapitaal beschikbaar.</h2></div><div><p className="large-copy">Een zakelijke MFP hoeft geen grote investering vooraf te zijn. We kunnen de apparatuur aanbieden via huur, lease of koop en het service- en verbruiksdeel meenemen in één voorstel.</p><div className="inline-actions"><Link className="btn btn-primary" href="/mfp-leasen">MFP leasen</Link><Link className="btn btn-secondary" href="/mfp-huren">MFP huren</Link><Link className="text-link" href="/mfp-kopen">MFP kopen →</Link></div></div></div></section>
<section className="container cta-section"><div className="cta-panel"><div><div className="eyebrow eyebrow-light">B2B ADVIES</div><h2>Laat ons uw printomgeving doorrekenen.</h2><p>Geef uw volume en wensen door. We helpen u met machine, contract en dienstverlening.</p></div><Link className="btn btn-light" href="/offerte">Ontvang een voorstel</Link></div></section>
</main>}