import Link from "next/link";
import {products} from "@/lib/products";
import MfpSelector from "@/components/MfpSelector";

export const metadata={title:"MFP's",description:"Bekijk en vergelijk Kyocera multifunctionals van ISELTO. Van compacte A4-modellen tot krachtige A3-systemen."};

export default function Products(){
 return <main>
  <section className="dark-hero products-hero"><div className="container hero-copy"><div className="eyebrow eyebrow-light">MFP SELECTEREN</div><h1>Kies de MFP die bij uw organisatie past.</h1><p>Bekijk het ISELTO-portfolio, gebruik de keuzehulp of vergelijk de belangrijkste eigenschappen en vraag direct een offerte aan voor een model dat aansluit op uw situatie.</p><div className="hero-actions"><Link className="btn btn-light" href="/vergelijker">Vergelijk modellen</Link><Link className="btn btn-outline-light" href="/offerte">Ik wil advies</Link></div></div></section>
  <section className="container editorial-section"><div className="section-head"><div><div className="eyebrow">SNEL NAAR</div><h2>Zoekt u een specifiek type MFP?</h2></div></div><div className="feature-grid"><Link className="card feature-card" href="/producten/a4-multifunctionals"><span>01</span><strong>A4 multifunctionals →</strong><small>Compacte zakelijke MFP's voor kantoorwerkgroepen.</small></Link><Link className="card feature-card" href="/producten/a3-multifunctionals"><span>02</span><strong>A3 multifunctionals →</strong><small>Meer papierformaten, capaciteit en afwerking.</small></Link><Link className="card feature-card" href="/producten/taskalfa-mz-serie"><span>03</span><strong>TASKalfa MZ-serie →</strong><small>De actuele A3-serie van 25 tot 70 ppm A4.</small></Link></div></section>
  <MfpSelector />
  <section className="container catalog-section"><div className="catalog-toolbar"><div><div className="eyebrow">KYOCERA PORTFOLIO</div><h2>{products.length} MFP-modellen.</h2></div><p>Van A4 kleur tot zware A3 zwart-wit productie. Elke productpagina bevat de beschikbare specificaties en documentatie.</p></div>
   <div className="product-grid catalog-grid">{products.map(p=><article className="card product-card" key={p.slug}><Link href={"/producten/"+p.slug} className="product-image-link"><div className="product-image"><img src={p.image} alt={p.name} className="product-image-element" loading="lazy"/></div></Link><div className="product-copy"><div className="eyebrow">{p.category}</div><h3>{p.name}</h3><p>{p.description}</p><div className="product-specs"><span>{p.speed}</span><span>{p.format}</span><span>{p.colour?"Kleur":"Zwart-wit"}</span></div><div className="product-actions"><Link className="text-link" href={"/producten/"+p.slug}>Specificaties →</Link><Link className="btn btn-primary" href={"/offerte?product="+p.slug}>Offerte</Link></div><a className="source-link" href={p.brochurePath} target="_blank" rel="noreferrer">Documentatie →</a></div></article>)}</div>
  </section>
  <section className="split-section"><div className="container split-grid"><div><div className="eyebrow">HULP BIJ UW KEUZE</div><h2>Twijfelt u tussen meerdere MFP's?</h2></div><div><p className="large-copy">U hoeft niet zelf alle technische verschillen uit te zoeken. Vertel ons hoe uw organisatie print en scant; wij helpen u de opties te bepalen.</p><Link className="btn btn-primary" href="/offerte">Vraag advies</Link></div></div></section>
 </main>
}