import Link from "next/link";
import {products} from "@/lib/products";
import MfpSelector from "@/components/MfpSelector";

export const metadata={title:"Zakelijke MFP's | A4 & A3 multifunctionals",description:"Bekijk zakelijke MFP's voor bedrijven: A4 en A3, kleur en zwart-wit. Vergelijk snelheid, formaat en functies en vraag advies over lease, huur of koop."};

export default function Products(){
 const itemListJsonLd={"@context":"https://schema.org","@type":"ItemList","name":"Zakelijke MFP's van Iselto","itemListElement":products.map((p,i)=>({"@type":"ListItem","position":i+1,"name":p.name,"url":"https://mfp.iselto.nl/producten/"+p.slug}))};
 const breadcrumbJsonLd={"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"MFP's","item":"https://mfp.iselto.nl/producten"}]};
 return <main>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(itemListJsonLd)}}/>
  <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbJsonLd)}}/>
  <section className="dark-hero products-hero"><div className="container hero-copy"><div className="eyebrow eyebrow-light">ZAKELIJKE MFP'S</div><h1>Zakelijke MFP's voor iedere werksituatie.</h1><p>Bekijk het Iselto-portfolio met A4- en A3-multifunctionals. Vergelijk modellen, gebruik de keuzehulp en vraag persoonlijk advies over de juiste configuratie.</p><div className="hero-actions"><Link className="btn btn-light" href="/mfp-kiezen">MFP keuzehulp</Link><Link className="btn btn-outline-light" href="/vergelijker">Vergelijk modellen</Link></div></div></section>
  <section className="container editorial-section"><div className="section-head"><div><div className="eyebrow">MFP CATEGORIEËN</div><h2>Zoekt u een specifiek type multifunctional?</h2></div></div><div className="feature-grid"><Link className="card feature-card" href="/producten/a4-multifunctionals"><span>01</span><strong>A4 multifunctionals →</strong><small>Compacte zakelijke MFP's voor kantoorwerkgroepen en afdelingen.</small></Link><Link className="card feature-card" href="/producten/a3-multifunctionals"><span>02</span><strong>A3 multifunctionals →</strong><small>Meer papierformaten, capaciteit en afwerking voor grotere werkstromen.</small></Link><Link className="card feature-card" href="/producten/taskalfa-mz-serie"><span>03</span><strong>TASKalfa MZ-serie →</strong><small>A3-modellen voor organisaties met hoge volumes en uitgebreide mogelijkheden.</small></Link></div></section>
  <MfpSelector/>
  <section className="container catalog-section"><div className="catalog-toolbar"><div><div className="eyebrow">MFP-PORTFOLIO</div><h2>{products.length} zakelijke MFP-modellen.</h2></div><p>Bekijk per model de specificaties, functies en mogelijkheden. Vanuit iedere productpagina kunt u door naar vergelijken, financiering, service en offerte.</p></div>
   <div className="product-grid catalog-grid">{products.map(p=><article className="card product-card" key={p.slug}><Link href={"/producten/"+p.slug} className="product-image-link"><div className="product-image"><img src={p.image} alt={p.name+" zakelijke MFP"} className="product-image-element" loading="lazy"/></div></Link><div className="product-copy"><div className="eyebrow">{p.category}</div><h3>{p.name}</h3><p>{p.description}</p><div className="product-specs"><span>{p.speed}</span><span>{p.format}</span><span>{p.colour?"Kleur":"Zwart-wit"}</span></div><div className="product-actions"><Link className="text-link" href={"/producten/"+p.slug}>Bekijk {p.name} →</Link><Link className="btn btn-primary" href={"/offerte?product="+p.slug}>Offerte</Link></div></div></article>)}</div>
  </section>
  <section className="split-section"><div className="container split-grid"><div><div className="eyebrow">HULP BIJ UW KEUZE</div><h2>Twijfelt u tussen meerdere MFP's?</h2></div><div><p className="large-copy">U hoeft niet zelf alle technische verschillen uit te zoeken. Vertel ons hoe uw organisatie print en scant; wij helpen u de opties te bepalen.</p><div className="feature-actions"><Link className="btn btn-primary" href="/offerte">Vraag MFP-advies</Link><Link className="text-link" href="/tco-scan">Bereken uw printkosten →</Link></div></div></div></section>
 </main>
}