import Link from "next/link";

const pillars=[
 {n:"01",title:"Inzicht",text:"Breng apparatuur, volumes, gebruikers en verbruik in kaart. Zo ontstaat een helder beeld van de huidige printomgeving."},
 {n:"02",title:"Beheer",text:"Maak tellerstanden, verbruik, toner en onderhoud voorspelbaar en beperk handmatig beheer."},
 {n:"03",title:"Beveiliging",text:"Bescherm vertrouwelijke documenten met authenticatie, printvrijgave en een inrichting die past bij uw organisatie."},
 {n:"04",title:"Optimalisatie",text:"Verminder onnodige apparatuur en verspilling en stem de omgeving af op werkplekken, locaties en printgedrag."},
];

export const metadata={title:"Managed Print",description:"Managed Print van Iselto: inzicht, beheer, beveiliging en optimalisatie van uw volledige printomgeving.",alternates:{canonical:"/managed-print"},openGraph:{type:"website",title:"Managed Print",description:"Managed Print van Iselto: inzicht, beheer, beveiliging en optimalisatie van uw volledige printomgeving.",url:"https://mfp.iselto.nl/managed-print"}};

export default function ManagedPrint(){
 return <main>
  <section className="dark-hero managed-hero"><div className="container hero-copy"><div className="eyebrow eyebrow-light">MANAGED PRINT</div><h1>Uw printomgeving geregeld.</h1><p>Niet alleen een goede MFP, maar een printomgeving die beheersbaar, veilig en voorspelbaar blijft. Iselto kijkt naar het totaal.</p><div className="hero-actions"><Link className="btn btn-light" href="/tco-scan">Start printerparkscan</Link><Link className="btn btn-outline-light" href="/service">Service & support</Link></div></div></section>
  <section className="container editorial-section"><div className="section-intro"><div><div className="eyebrow">VAN MACHINE NAAR OMGEVING</div><h2>Print is onderdeel van uw werkplek.</h2></div><div><p className="lead">Een printerpark groeit gemakkelijk zonder dat iemand het overzicht houdt. Wij brengen apparatuur, gebruik en processen samen en maken daar één beheersbare omgeving van.</p><Link className="text-link" href="/oplossingen">Bekijk alle oplossingen →</Link></div></div><div className="solution-grid">{pillars.map(p=><article className="solution-card" key={p.n}><div className="solution-number">{p.n}</div><h3>{p.title}</h3><p>{p.text}</p></article>)}</div></section>
  <section className="dark-band"><div className="container band-grid"><div><div className="eyebrow eyebrow-light">PRAKTISCH BEHEER</div><h2>Van toner tot rapportage.</h2></div><p>Afhankelijk van de inrichting kunnen monitoring, tellerstanden, tonerlevering, onderhoud en rapportage onderdeel zijn van de dienstverlening. De precieze scope leggen we vooraf vast.</p></div></section>
  <section className="container editorial-section"><div className="section-intro"><div><div className="eyebrow">HOE WE STARTEN</div><h2>Begin met een printerparkscan.</h2></div><p className="lead">We brengen aantallen, locaties, modellen, volumes, contracten en gebruik in kaart. Daarna bespreken we welke apparatuur, software en service logisch bij elkaar horen.</p></div><div className="hub-grid"><Link className="hub-card" href="/tco-scan"><strong>TCO-scan</strong><span>Breng maand- en jaarlasten indicatief in beeld.</span></Link><Link className="hub-card" href="/mfp-kiezen"><strong>MFP keuzehulp</strong><span>Bekijk welke modellen bij de werksituatie passen.</span></Link><Link className="hub-card" href="/vergelijker"><strong>MFP vergelijker</strong><span>Leg maximaal drie modellen naast elkaar.</span></Link><Link className="hub-card" href="/service"><strong>Service & support</strong><span>Regel een storing, toner, tellerstand of onderhoud.</span></Link></div></section>
  <section className="container cta-section"><div className="cta-panel"><div><div className="eyebrow eyebrow-light">PRINTERPARK ANALYSE</div><h2>Wat kost uw huidige printomgeving?</h2><p>Laat apparatuur, gebruik en dienstverlening samen bekijken.</p></div><Link className="btn btn-light" href="/offerte">Vraag een analyse aan</Link></div></section>
 </main>;
}