import Link from "next/link";
import {notFound} from "next/navigation";
const pages={
"zakelijke-dienstverlening":{title:"MFP voor zakelijke dienstverlening",h:"Print en scan zonder dat het uw werk vertraagt.",text:"Voor advieskantoren, financiële dienstverlening, advocaten, administratie en andere zakelijke dienstverleners zijn betrouwbare print- en scanprocessen onderdeel van de dagelijkse werkplek.",points:["Beveiligd printen voor vertrouwelijke documenten","Snelle scanflows naar e-mail, cloud of dossier","A4 en A3 voor dagelijkse en specialistische documenten","Lease, huur of koop met passende service"]},
"zorg-welzijn":{title:"MFP voor zorg en welzijn",h:"Veilig omgaan met documenten in zorg en welzijn.",text:"Zorgorganisaties werken met vertrouwelijke informatie en verschillende gebruikers. De printomgeving moet daarom betrouwbaar, beheersbaar en veilig zijn.",points:["Authenticatie en beveiligde printvrijgave","Scannen naar digitale dossiers en workflows","Beheer van meerdere locaties en gebruikers","All-in service en continuïteit"]},
"onderwijs":{title:"MFP voor onderwijs",h:"Een printomgeving die meebeweegt met leerlingen, medewerkers en locaties.",text:"Onderwijsorganisaties hebben pieken, veel gebruikers en verschillende printbehoeften. Een passende MFP-oplossing maakt beheer overzichtelijker.",points:["Gebruikers- en printbeheer","Kleur en zwart-wit voor lesmateriaal","Cloud en mobiel printen","Kostenbeheersing en monitoring"]},
"industrie-techniek":{title:"MFP voor industrie en techniek",h:"Van kantoor tot technische documentatie.",text:"Technische organisaties combineren kantoorwerk met documenten, tekeningen, handleidingen en projectinformatie. De printomgeving moet daarbij passen.",points:["A3 voor technische documenten","Hoge volumes en productiviteit","Scannen en documentrouting","Robuuste service en continuïteit"]},
"handel-logistiek":{title:"MFP voor handel en logistiek",h:"Documenten snel verwerken in een dynamische organisatie.",text:"Orderdocumenten, pakbonnen, facturen en interne communicatie vragen om een print- en scanomgeving die efficiënt blijft werken.",points:["Snelle print- en scanprocessen","OCR en documentverwerking","Output management","Flexibele huur- en leaseoplossingen"]},
"mkb":{title:"MFP voor het MKB",h:"Professioneel printen zonder onnodige complexiteit.",text:"Voor veel MKB-organisaties is de multifunctional een centrale werkplekvoorziening. Wij helpen met een passende machine en een overzichtelijk contract.",points:["A4 of A3, kleur of zwart-wit","Keuzehulp op basis van printvolume","Lease, huur of koop","All-in service en ondersteuning"]}
} as const;
export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=pages[slug as keyof typeof pages];return p?{title:p.title,description:p.text}:{};}
export default async function Branche({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=pages[slug as keyof typeof pages];if(!p)notFound();return <main>
<section className="dark-hero"><div className="container hero-copy"><div className="eyebrow eyebrow-light">ZAKELIJKE MFP · {p.title.replace("MFP voor ","").toUpperCase()}</div><h1>{p.h}</h1><p>{p.text}</p><div className="hero-actions"><Link className="btn btn-light" href="/producten#mfp-kiezen">Vind uw MFP</Link><Link className="btn btn-outline-light" href="/offerte">Vraag advies</Link></div></div></section>
<section className="container editorial-section"><div className="section-intro"><div><div className="eyebrow">UW SITUATIE</div><h2>Een printoplossing die aansluit op uw werk.</h2></div><p className="lead">We beginnen met uw volumes, gebruikers, documenten en processen. Daarna bepalen we apparatuur, software, financiering en service.</p></div><div className="selector-benefits">{p.points.map((x,i)=><article key={x}><strong>0{i+1}</strong><span>{x}</span></article>)}</div></section>
<section className="split-section"><div className="container split-grid"><div><div className="eyebrow">ONTZORGEN</div><h2>Van MFP tot documentworkflow.</h2></div><div><p className="large-copy">Naast apparatuur kunnen software, beveiligd printen, OCR, workflow, cloud print en managed print onderdeel zijn van de oplossing.</p><Link className="btn btn-primary" href="/software">Bekijk software</Link></div></div></section>
<section className="container cta-section"><div className="cta-panel"><div><div className="eyebrow eyebrow-light">B2B ADVIES</div><h2>Wat heeft uw organisatie nodig?</h2><p>Vertel ons uw situatie. We helpen u met een passende MFP en dienstverlening.</p></div><Link className="btn btn-light" href="/offerte">Offerte aanvragen</Link></div></section>
</main>}